name: tests

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setupJava
        uses: actions/setup-java@v1
        with:
          java-version: 17

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tests
        run: mvn test
